/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
        './src/components/**/*.{js,ts,jsx,tsx,mdx}',
        './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    ],
    safelist: [
        // Column span classes
        'col-span-1',
        'col-span-2',
        'col-span-3',
        'col-span-4',
        'col-span-5',
        'col-span-6',
        '[@media(min-width:768px)_and_(min-aspect-ratio:1/1)]:col-span-1',
        '[@media(min-width:768px)_and_(min-aspect-ratio:1/1)]:col-span-2',
        '[@media(min-width:768px)_and_(min-aspect-ratio:1/1)]:col-span-3',
        '[@media(min-width:768px)_and_(min-aspect-ratio:1/1)]:col-span-4',
        '[@media(min-width:768px)_and_(min-aspect-ratio:1/1)]:col-span-5',
        '[@media(min-width:768px)_and_(min-aspect-ratio:1/1)]:col-span-6',
        '[@media(max-height:600px)_and_(max-width:768px)]:col-span-1',
        '[@media(max-height:600px)_and_(max-width:768px)]:col-span-2',
        '[@media(max-height:600px)_and_(max-width:768px)]:col-span-3',
        '[@media(max-height:600px)_and_(max-width:768px)]:col-span-4',
        '[@media(max-height:600px)_and_(max-width:768px)]:col-span-5',
        '[@media(max-height:600px)_and_(max-width:768px)]:col-span-6',
        // Row span classes
        'row-span-1',
        'row-span-2',
        'row-span-3',
        'row-span-4',
        'row-span-5',
        'row-span-6',
        '[@media(min-width:768px)_and_(min-aspect-ratio:1/1)]:row-span-1',
        '[@media(min-width:768px)_and_(min-aspect-ratio:1/1)]:row-span-2',
        '[@media(min-width:768px)_and_(min-aspect-ratio:1/1)]:row-span-3',
        '[@media(min-width:768px)_and_(min-aspect-ratio:1/1)]:row-span-4',
        '[@media(min-width:768px)_and_(min-aspect-ratio:1/1)]:row-span-5',
        '[@media(min-width:768px)_and_(min-aspect-ratio:1/1)]:row-span-6',
        '[@media(max-height:600px)_and_(max-width:768px)]:row-span-1',
        '[@media(max-height:600px)_and_(max-width:768px)]:row-span-2',
        '[@media(max-height:600px)_and_(max-width:768px)]:row-span-3',
        '[@media(max-height:600px)_and_(max-width:768px)]:row-span-4',
        '[@media(max-height:600px)_and_(max-width:768px)]:row-span-5',
        '[@media(max-height:600px)_and_(max-width:768px)]:row-span-6',
        // Grid template classes
        'grid-cols-2',
        '[@media(min-width:768px)_and_(min-aspect-ratio:1/1)]:grid-cols-6',
        '[@media(max-height:600px)_and_(max-width:768px)]:grid-cols-4',
        'auto-rows-[20vh]',
        '[@media(min-width:768px)_and_(min-aspect-ratio:1/1)]:auto-rows-[25vh]',
        '[@media(max-height:600px)_and_(max-width:768px)]:auto-rows-[15vh]',
    ],
    theme: {
        extend: {},
        screens: {
            'sm': '640px',
            'md': '768px',
            'lg': '1024px',
            'xl': '1280px',
            '2xl': '1536px',
        }
    },
    plugins: [],
}