name = "fw-hale"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
routes = [
  { pattern = "fw-hale.pages.dev/*", zone_name = "fw-hale.pages.dev" }
]

[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

# Cloudflare Pages configuration
pages_build_output_dir = "/.vercel/output/static"

# Ensure static assets are included
[build.upload]
dir = "/.vercel/output/static"
include = ["**/*"]
exclude = ["node_modules"]

# Environment variables
[vars]
NODE_VERSION = "20"
