import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Preloader from '@/components/Preloader';
import { PreloaderProvider } from '@/components/PreloaderContext';
import { VisualEditing } from "next-sanity";
import { draftMode } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FutureWorld",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { isEnabled } = await draftMode();
  
  return (
    <html lang="en"  className="scroll-smooth">
      <body suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <PreloaderProvider>
          <Preloader />
          {children}
          {isEnabled && (
            <VisualEditing trailingSlash={false} />
          )}
        </PreloaderProvider>
      </body>
    </html>
  );
}
